# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/frmMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(1042, 766)
        frmMain.setWindowTitle("")
        frmMain.setStyleSheet("border-image: url(:/ArkaFon/resimler/bursa.png);")
        self.centralwidget = QtWidgets.QWidget(frmMain)
        self.centralwidget.setObjectName("centralwidget")
        frmMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        pass
import Resources_rc
