# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/frmMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMenu(object):
    def setupUi(self, frmMenu):
        frmMenu.setObjectName("frmMenu")
        frmMenu.resize(1192, 824)
        frmMenu.setStyleSheet("background-color: rgb(0, 160, 255);")
        self.graphicsView = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView.setGeometry(QtCore.QRect(380, 450, 431, 111))
        self.graphicsView.setStyleSheet("border-image: url(:/ArkaFon/resimler/logo-white.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_2.setGeometry(QtCore.QRect(80, 400, 200, 200))
        self.graphicsView_2.setStyleSheet("border-image: url(:/ArkaFon/resimler/biyografi.png);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_3.setGeometry(QtCore.QRect(290, 200, 200, 200))
        self.graphicsView_3.setStyleSheet("border-image: url(:/ArkaFon/resimler/dram.png);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_4.setGeometry(QtCore.QRect(510, 200, 200, 200))
        self.graphicsView_4.setStyleSheet("border-image: url(:/ArkaFon/resimler/masal.png);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_5.setGeometry(QtCore.QRect(730, 200, 200, 200))
        self.graphicsView_5.setStyleSheet("border-image: url(:/ArkaFon/resimler/siir.png);")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_6.setGeometry(QtCore.QRect(890, 400, 200, 200))
        self.graphicsView_6.setStyleSheet("border-image: url(:/ArkaFon/resimler/hikayeler.png);")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_7.setGeometry(QtCore.QRect(730, 600, 200, 200))
        self.graphicsView_7.setStyleSheet("border-image: url(:/ArkaFon/resimler/tarihi.png);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_8.setGeometry(QtCore.QRect(510, 600, 200, 200))
        self.graphicsView_8.setStyleSheet("border-image: url(:/ArkaFon/resimler/sohbet.png);")
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_9 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_9.setGeometry(QtCore.QRect(290, 600, 200, 200))
        self.graphicsView_9.setStyleSheet("border-image: url(:/ArkaFon/resimler/pratik.png);")
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_10 = QtWidgets.QGraphicsView(frmMenu)
        self.graphicsView_10.setGeometry(QtCore.QRect(370, 20, 451, 191))
        self.graphicsView_10.setStyleSheet("border-image: url(:/ArkaFon/resimler/baslik.png);")
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.label = QtWidgets.QLabel(frmMenu)
        self.label.setGeometry(QtCore.QRect(990, 10, 190, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")

        self.retranslateUi(frmMenu)
        QtCore.QMetaObject.connectSlotsByName(frmMenu)

    def retranslateUi(self, frmMenu):
        _translate = QtCore.QCoreApplication.translate
        frmMenu.setWindowTitle(_translate("frmMenu", "Form"))
        self.label.setText(_translate("frmMenu", "18.02.2026 16:08:27"))
import Resources_rc
