# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/frmReklam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmReklam(object):
    def setupUi(self, frmReklam):
        frmReklam.setObjectName("frmReklam")
        frmReklam.resize(1003, 735)
        frmReklam.setStyleSheet("border-image: url(:/ArkaFon/resimler/Main.png);")

        self.retranslateUi(frmReklam)
        QtCore.QMetaObject.connectSlotsByName(frmReklam)

    def retranslateUi(self, frmReklam):
        _translate = QtCore.QCoreApplication.translate
        frmReklam.setWindowTitle(_translate("frmReklam", "Reklam Alanı"))
import Resources_rc
